### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by ghost** [hasanbarary/shopping_list#1]
## Naming Convention
It's better to use good naming.

### Code review
for example instead of using shopping_list, use items.
**Note:** help is a function in python and it is not a good practice to use that name. please choose another name for that.

> The last thing I want to mention is that use your functions into a single file for this project. It is not necessary to use other modules with a single function. it's not best practice.

**Comment by hasanbarary** [comment]
hi
I have done it
Thanks for the attention
