### ISSUE TITLE
More Challenges

### ISSUE THREAD

**Issue by ghost** [hasanbarary/shopping_list#2]
# Challenge
here we have some challenges to add into your shopping list code.

1. CRUD
   1. already you write the Create and read methods.
   2. please write edit function into your shopping list.
      * for example user select an item, then he/she update that specific item.
   3. the last functionality of this issue is creating remove method. user select an specific item and request he/she wants to remove that item. finally you ask "are you sure to removing {} item?" if the user writes yes, you remove the item else you get back onto shoppinglist.

**NOTE:** dear hasan, at first please fix your previous code. Then write a report when a user added an item. for example he added an apple and you write this sentence: ' you added {item} into your list. Now you have {count_of_list} items.'.

If you complete this issue, you can get a new challenge.

Good luck

**Comment by hasanbarary** [comment]
Hi 
Ok.

**Comment by hasanbarary** [comment]
Salam
change add Item message and show count of element in items list

**Comment by hasanbarary** [comment]
add 'remove function'

**Comment by hasanbarary** [comment]
add 'Edit Function'

**Comment by hasanbarary** [comment]
add 'are you sure to removing' to code
