### ISSUE TITLE
creative minded

### ISSUE THREAD

**Issue by ghost** [hasanbarary/shopping_list#3]
**Congratulation, you passed two challenges in a day.**
#2 

> You are so good. Keep going

Here we have some new challenges:

- [x]  items can have a category.

    * For example, orange and apple are items of a citrus category. Then, milk and sugar are items of supermarket category.

- [x]     You need show items of a category.

- [x]     You can implement Update and Delete options for the category.

### Tips:
1. You can define items globally at the first line of your program. The benefit is that you don't need to send an argument like items into your functions.
2. If I enter a number, in the other words you have to accept just alphabet and ignore any number when the user is answering to your program.
3.  How do you manage if the user says how much milk he/she wants?
4. You need to show the list within a for loop. Not just showing the list. it is not user friendly.

#1 
append_list --> add_item
edit --> edit_item

**Comment by hasanbarary** [comment]
Tips 
1,2 Done

**Comment by hasanbarary** [comment]
Tips 3 done  

commit ID: cd1c0243ef0d1fe66751bec49efdcac9258234e1

**Comment by hasanbarary** [comment]
08482137c39dded543eda006357987f1ee912c59

Add category And Show is Done

**Comment by ghost** [comment]
Well done,

you passed many tasks. For now, you need to focus on new exercises (dungeon, number guess, letter guess and pass gen)

> if you finished Those exercises, you can continue this project. So, it is not necessary to continue your code in this repository. If you have time and want a challenge you can start challenge 4.
